### ISSUE TITLE
Issue running Polymer Started Kit 1.0.0

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/polymer-starter-kit#110]
I downloaded polymer-starter-kit-dependencies-checked-in-1.0.0.zip and tried gulp serve. I got an "Unhandled rejection Error". I bypassed this by adding an error handler for the "images" gulp task and printed the error to console. The error I see is below:

Error in plugin 'gulp-cache'
Message:
    spawn ENOENT
Details:
    code: ENOENT
    errno: ENOENT
    syscall: spawn
    fileName: /Users/abishek/work/dev/onroad/onroad-polymer/app/images/touch/apple-touch-icon.png

Though the server started up after handling the error, wondering what needs to be done here to fix this nicely.

**Comment by addyosmani** [comment]
Someone else ran into this yesterday and worked around it by deleting the images directory. Could you confirm whether you run into this issue with the non checked in deps version too?

**Comment by nafem** [comment]
I get a similar unhandled error event. If I comment out the image caching in gulpfile.js, it completes the build but then throws:


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by addyosmani** [comment]
@nafem are you using the version with checked in deps or without?

**Comment by nafem** [comment]
With checked in deps. Running Ubuntu 14.04
I have also tried without deps but get the following error when running npm install

npm WARN package.json polymer-starter-kit@0.0.0 No repository field....


npm ERR! web-component-tester@3.1.3 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the web-component-tester@3.1.3 postinstall script.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/platform/polymer-starter-non-dep/polymer-starter-kit-1.0.1
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

But this is probably a different issue

**Comment by addyosmani** [comment]
@nafem it looks like you have an older version of Node and npm. Could you upgrade to the latest Node and try again? https://nodejs.org/

**Comment by fones** [comment]
After upgrading node to last version problem still occurs (macosx)
When comment out this line
`.pipe($.cache($.imagemin({ progressive: true, interlaced: true })))`
it works!

**Comment by koenhendriks** [comment]
I'm running Linux Mint 17 with latest NodeJs.
I tried this with the checked in dependencies version 1.0.1 and i still have this issue.

Here is the log:
```
[20:54:57] Using gulpfile ~/PhpstormProjects/Polymer-kit/gulpfile.js
[20:54:57] Starting 'styles'...
[20:54:58] Starting 'elements'...
[20:54:58] Starting 'images'...
[20:54:58] 'elements' all files 0 B
[20:54:58] Finished 'elements' after 819 ms
Unhandled rejection Error: spawn /home/koen/PhpstormProjects/Polymer-kit/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
[20:54:58] 'styles' all files 98 B
[20:54:58] Finished 'styles' after 1.18 s
```

if i comment out ```.pipe($.cache($.imagemin({ progressive: true, interlaced: true })))``` i get a new error:

```
[20:55:43] Using gulpfile ~/PhpstormProjects/Polymer-kit/gulpfile.js
[20:55:43] Starting 'styles'...
[20:55:43] Starting 'elements'...
[20:55:43] Starting 'images'...
[20:55:43] 'elements' all files 0 B
[20:55:43] Finished 'elements' after 20 ms
[20:55:43] 'styles' all files 98 B
[20:55:43] Finished 'styles' after 362 ms
[20:55:43] 'images' all files 25.09 kB
[20:55:43] Finished 'images' after 67 ms
[20:55:43] Starting 'serve'...
[20:55:43] Finished 'serve' after 46 ms
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.2.3:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.2.3:3001
 ------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: app
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at module.exports (/home/koen/PhpstormProjects/Polymer-kit/node_modules/opn/index.js:58:24)
    at Object.utils.open (/home/koen/PhpstormProjects/Polymer-kit/node_modules/browser-sync/lib/utils.js:170:23)
    at Object.utils.openBrowser (/home/koen/PhpstormProjects/Polymer-kit/node_modules/browser-sync/lib/utils.js:160:23)
    at EventEmitter.events.service:running (/home/koen/PhpstormProjects/Polymer-kit/node_modules/browser-sync/lib/internal-events.js:45:23)
    at EventEmitter.emit (events.js:129:20)
    at /home/koen/PhpstormProjects/Polymer-kit/node_modules/browser-sync/lib/browser-sync.js:260:19
    at /home/koen/PhpstormProjects/Polymer-kit/node_modules/browser-sync/node_modules/async-each-series/index.js:15:40
```

**Comment by addyosmani** [comment]
@koenhendriks does this issue happen with the non-checked in deps version too?

**Comment by koenhendriks** [comment]
@addyosmani just tested, I don't get any errors with the non-checked in deps.

**Comment by addyosmani** [comment]
Thanks for confirming. I think we may be out of luck with the checked-in dependencies version. When we would generate the zip for it on a *nix machine, Windows users would run into issues with similar errors and when generating on Windows, the opposite appears to happen. 

To minimize confusion, I'm considering deprecating the checked-in deps version as an option for now.

@fones you mentioned you were on Mac. Did you have any issues with the non-checked in deps version?

**Comment by fones** [comment]
@addyosmani I've tried only without deps. I've checked out master branch at commit `6078e4e7b6` and only issue with `.pipe($.cache($.imagemin({ progressive: true, interlaced: true })))` occurs.

**Comment by addyosmani** [comment]
Hey folks. If you're still running into this issue, I just wanted to mention we've updated our README to be a little more specific with Node versions. We currently recommend Node 0.12.x and above. To check/update accordingly, please see https://github.com/PolymerElements/polymer-starter-kit#prerequisites-for-everyone

**Comment by arthurvr** [comment]
Is anyone still having this issue on latest Node using the latest PSK?

**Comment by cyberabis** [comment]
With the latest kit, this is solved for me.

**Comment by addyosmani** [comment]
Thanks @cyberabis. Would be great to get a few more confirmations and we can then close this.

**Comment by koenhendriks** [comment]
Worked for me to!
