### ISSUE TITLE
Menu not working properly in Firefox 38.0.5

### ISSUE THREAD

**Issue by Cammisuli** [PolymerElements/polymer-starter-kit#166]
Windows Firefox 38.0.5
The menu does not work as expected. 

When you click a space that does not contain text, the page changes. If you click the text, only the menu selection changes and the page content does not. 

Clicking the text again triggers a page change. 

![firefoxmenubug](https://cloud.githubusercontent.com/assets/4332460/8138882/e8079c32-111c-11e5-99ff-0db2a22bc92d.gif)

**Comment by addyosmani** [comment]
Could you verify whether you have any Web Components related flags turned on in Firefox 38?

**Comment by Cammisuli** [comment]
It's set on default. Interestingly enough, setting it to true caused the site to never load.
![firefoxwebcomponents](https://cloud.githubusercontent.com/assets/4332460/8145880/769194dc-11e8-11e5-985a-2988b8e8439e.png)

**Comment by addyosmani** [comment]
@notwaldorf In PSK, we're currently using the advice for (better) a11y focus styling that we get from using this setup with `paper-menu` (links rather than paper-item):

```
        <!-- Drawer Content -->
        <paper-menu class="list" attr-for-selected="data-route" selected="{{route}}" on-iron-select="onMenuSelect">
          <a data-route="home" href="/">
            <iron-icon icon="home"></iron-icon>
            <span>Home</span>
          </a>

          <a data-route="users" href="/users">
            <iron-icon icon="info"></iron-icon>
            <span>Users</span>
          </a>

          <a data-route="contact" href="/contact">
            <iron-icon icon="mail"></iron-icon>
            <span>Contact</span>
          </a>
        </paper-menu>
```

This of course doesn't use `paper-item` which doesn't run into the issue noted by the OP. Should `paper-menu` be providing a fix here or should we be providing a custom fix?

**Comment by gertcuykens** [comment]
Can you remove the question tag please and mark it bug please preferably p0 :p

**Comment by gertcuykens** [comment]
Does not fix the problem in Safari

```
        <paper-menu class="list" attr-for-selected="data-route" selected="{{route}}" on-iron-select="onMenuSelect">
          <paper-item data-route="home">
            <iron-icon icon="home"></iron-icon>
            <span>About</span>
          </paper-item>
          <paper-item data-route="maps">
            <iron-icon icon="maps:place"></iron-icon>
            <span>Maps</span>
          </paper-item>
          <paper-item data-route="trackers">
            <iron-icon icon="device:gps-fixed"></iron-icon>
            <span>Trackers</span>
          </paper-item>
          <paper-item data-route="contact">
            <iron-icon icon="mail"></iron-icon>
            <span>Contact</span>
          </paper-item>
        </paper-menu>
```

**Comment by chuckh** [comment]
It looks like this is a bug with `paper-menu`.  See paper-menu issues:  https://github.com/PolymerElements/paper-menu/issues/27 and https://github.com/PolymerElements/paper-menu/issues/31.

**Comment by vorcigernix** [comment]
Fixed in firefox by using icon-item:
```
        <!-- Drawer Content -->
        <paper-menu class="list" attr-for-selected="data-route" selected="{{route}}" on-iron-select="onMenuSelect">
          <paper-icon-item  data-route="home" href="/">
            <iron-icon icon="home"></iron-icon>
            Home
          </paper-icon-item>

          <paper-icon-item data-route="users" href="/users">
            <iron-icon icon="info"></iron-icon>
            Users
          </paper-icon-item>

          <paper-icon-item data-route="contact" href="/contact">
            <iron-icon icon="mail"></iron-icon>
            Contact
          </paper-icon-item>
        </paper-menu>
      </paper-scroll-header-panel>
```

**Comment by chuckh** [comment]
I tested the above code on PSK master and did not fix the problem.  

When clicking on a menu item for a second time in Firefox Mac and Safari Mac the `onDataRouteClick` in app.js, `select` and `_focusedItemChanged` in iron-menu-behavior don't fire on first click only second. This maybe related https://github.com/PolymerElements/iron-menu-behavior/issues/13. 

The menu works correctly for Chrome Mac and Mobile Safari.

**Comment by Steve17756** [comment]
Agree with chuck. Also works on Chrome Win.

**Comment by samccone** [comment]
Tested on firefox 41 with the latest install of everything and things seem A-OK

We can reopen if anyone can reproduce :) :sparkles:

**Comment by GXLabonte** [comment]
Using Firefox 4.1.01, page.js 1.6.4, updated bower components, problem is now intermittent.  Sometimes a single click works but not always.   Could be a problem with page.js  I've only seen this when using page.js (their history.md file does mention a bug  fix with click-event in Firefox for version 1.6.3)

**Comment by ahuezo** [comment]
Found a workarround for firefox:

style the span an iron-icon with pointer-events: none

Tested on firefox 41, linux

**Comment by GXLabonte** [comment]
style the span and iron-icon with pointer-events: none

Tested and works for me.

Thanks

**Comment by addyosmani** [comment]
Is anyone able to reproduce this using Firefox 44+ (Nightlies)?

**Comment by vorcigernix** [comment]
I am able to reproduce in latest Safari.
Dne 12. 10. 2015 12:20 PM napsal uživatel "Addy Osmani" <
notifications@github.com>:

**Comment by JoernT** [comment]
i can confirm that the above mentioned trick with styling pointer-events:none; works in FF 44.01 on Mac.

**Comment by samccone** [comment]
@notwaldorf I think i saw a PR from you to resolve this yesterday right?

**Comment by victoriaSh** [comment]
Using more-routing. Had the same issue with double click. 
Styling all elements inside `<paper-item>`(even  `<a href="{{ urlFor('home')}}">`) works for me. 
But I guess urlFor will not work in future If I decide to pass params.

**Comment by sbley** [comment]
Styling the paper-item's span with `pointer-events: none;` also helps when you have `<paper-item>`s in an `iron-list`. If you don't disable the pointer-events you can't click the span text in IE11.
```
<iron-list items="[[profiles]]" as="p">
  <template>
    <paper-item>
      <span>{{p.name}}</span>
    </paper-item>
  </template>
</iron-list>
```

**Comment by chuckh** [comment]
thanks to @rubenstolk work around (https://github.com/PolymerElements/paper-menu/issues/27#issuecomment-152212292) we can fix this problem by adding: 

```
paper-menu a > *, paper-menu paper-item > *, paper-menu paper-icon-item > * {
  pointer-events: none!important;
}
```

to shared-styles.html.

**Comment by rubenstolk** [comment]
@addyosmani I feel this should be rather fixed in `paper-menu`, I've submitted a PR there https://github.com/PolymerElements/paper-menu/pull/57, perhaps @notwaldorf can help out...

**Comment by sbley** [comment]
@rubenstolk Have you seen my comment above? https://github.com/PolymerElements/polymer-starter-kit/issues/166#issuecomment-150623963
The missing `pointer-events: none` within paper-items also causes problems using an iron-list instead of paper-menu. So I wonder where the fix should go.

**Comment by rubenstolk** [comment]
No I hadn't really seen that/thought of that. @cdata is apparently the one who is going to look into this, let's wait for his response then.

**Comment by code2be** [comment]
I think that fix should be applied to all paper-icon-item and paper-item even if not inside a paper-menu ?

**Comment by sbley** [comment]
@code2be Exactly!

**Comment by diddledan** [comment]
I get this problem using ONLY iron-menubar-behaviour in my custom element so the issue is there and not in the paper elements.
