### ISSUE TITLE
404 Not Found if `hashbang = false` 

### ISSUE THREAD

**Issue by teckays** [PolymerElements/polymer-starter-kit#201]
A problem here. If I set `hasbang=false` in `routing.html` and click a link then the route is matched and appropriate content is shown, however if I refresh a page with a route other than `/` then `browserSync` returns `404`. Is there a way to configure PSK to work with `hashbang=false`?

Thanks.

**Comment by SilverPaladin** [comment]
This is a function of your server config and not related to polymer.  Have a look at the apache mod rewrite settings related to rewiting urls to always load up index.html. Loading the urls the way you describe won't work with the local server.

**Comment by arthurvr** [comment]
@SilverPaladin why do you think this isn't related? I think he's just talking about our routing system not about some kind of backend.

**Comment by SilverPaladin** [comment]
Are you daying service worker will take care of this situation?

**Comment by MarkArts** [comment]
Hey, 
I was having the same problem and fixed it the following way:

**Fixing browsersync**
I found the following [issue](https://github.com/BrowserSync/browser-sync/issues/204) in the browsersync repo.
The solution provided here is to use [connect-history-api-fallback]( https://github.com/bripkens/connect-history-api-fallback).
In gulpfile.js you should add the following 
`var historyApiFallback = require('connect-history-api-fallback')`
and change the server property of browsersync in the serve task to
    
    server: {
      baseDir: ['.tmp', 'app'],
      middleware: [ historyApiFallback() ],
      routes: {
        '/bower_components': 'bower_components'
      }
    }`
Then you should change the the server property of browsersync in the server:dist task to

    server: {
      baseDir: ['dist'],
      middleware: [ historyApiFallback() ]
    }

**Fixing the dist**
I found the following [stackoverflow question](http://stackoverflow.com/questions/22739455/htaccess-redirect-for-angular-routes) about angular routes and the answer given there seems to work for me.
You need to add the following to your .htacces file

    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    RewriteRule ^(.*) /index.html [NC,L]

To use the .htacces in your app folder instead of the apache-server-configs .htacces.  you should remove `'node_modules/apache-server-configs/dist/.htaccess'` from the copy task in the gulpfile.js
leaving:

     var app = gulp.src([
       'app/*',
       '!app/test',
       '!app/precache.json',   
    ]

I'm not sure if modifiying the .htaccess is a good idea but i see no harm in using [connect-history-api-fallback]( https://github.com/bripkens/connect-history-api-fallback)

**Comment by addyosmani** [comment]
@MarkArts I've been using a similar workaround to start putting together a solution for #66. The one issue I've found using connect-history-api-fallback is that whilst this works fine for top-level routes (/about, /home, /contact) as soon as you try it with any more complex routes (e.g /users/rob) you run into the same problem. Curious if you're experienced the same issue in your testing.

**Comment by MarkArts** [comment]
Hey i don't use top level routes but i just tried it and i got a black screen.

I did come across [connect-modrewrite](https://www.npmjs.com/package/connect-modrewrite) but using connect-history-api-fallback seemed easier to use. Maybe 

I also came across [gulp-connect](https://github.com/AveVlad/gulp-connect) and tried using it as server with the fallback option (and setup browsersync as proxy to it).

    gulp.task('connect', function() {
      $.connect.server({
        root: 'dist',
        fallback: 'dist/index.html',
        livereload: true,
        port: 3010
      });
    });

which does redirect /user/rob to index.html but it causes a [infinite loop in loading webcomponents.js](http://i.imgur.com/XFVHczI.png) somehow.

**Comment by addyosmani** [comment]
Thanks for testing `gulp-connect` out. It looks like although it covers the /user/rob correct, we're obviously not going to want to deal with the infinite loop issue atm. 

Unless we can come up with a better setup, we'll probably go ahead with the `connect-history-api` fallback approach as it's a little more reliable than what we have today.

**Comment by bendavis78** [comment]
The `connect-history-api` fix doesn't seem to handle paths more than one level deep. For example, `/foo` works fine, but when you load the page with `/foo/bar`, all paths break since they are no longer relative to root. Theoretically this should be fixable using `<base href="/">`. however I don't think polymer respects the base href attribute.

**Comment by moderndeveloperllc** [comment]
@addyosmani Any progress on this? Pretty URLs aren't of much use if you can't bookmark them and come back to that spot. Is this more of a page.js issue?

**Comment by geopaulm** [comment]
@bendavis78 @moderndeveloperllc I am also facing the same issue. Is there any fix on this?

**Comment by chuckh** [comment]
I got pretty URLS working on Firebase.com hosting by doing the following:  

**- Adding below rewrites rules to firebase.json**
```
  "firebase": "polymer-starter-kit",
  "public": "dist",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**"
  ],
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]
}
```

**- Added `<base href="/">` to `head` in index.html**

**-  Set `hashbang: true` in routing.html**

You can see this working at https://polymer-starter-kit.firebaseapp.com/users/Chuck

It also works with `gulp serve` and `gulp serve:dist`! :fireworks: :dancer: :smiley:

**Comment by addyosmani** [comment]
Nice, @chuckh! For others running into these issues, I'd be curious if the last two steps here are of any help in solving what you were experiencing.

**Comment by chuckh** [comment]
You set **Set `hashbang: false`** in routing.html not true.  I fixed my above comment to reflect that.

**Comment by rycastaneda** [comment]
@chuckh is your solution only applicable to firebase hosting? I am still having problems with the one level deep in api fallback

**Comment by samccone** [comment]
@rycastaneda what version of PSK are you on?

**Comment by rycastaneda** [comment]
@samccone PSK 1.2.0

**Comment by samccone** [comment]
you will want this commit :)
https://github.com/PolymerElements/polymer-starter-kit/commit/7082366bc258ae748837d3adfe754e70955180f9

**Comment by samccone** [comment]
(on a side note I am going to close this issue because I am pretty sure this is a solved problem )

We can reopen if it is not :+1: Thanks all!

**Comment by bkawk** [comment]
How can this be marked as solved, this issue still exists.

**Comment by robdodson** [comment]
I don't know much about AWS but it needs to redirect every page to index.html, not just `/`. I would imagine something like `/*` but I don't know how they do their regex.

**Comment by dman777** [comment]
What about when using `historyFallback()` with `Polymer.Base.importHref()`? Without using hashes, `historyFallback` is ineffective with  `Polymer.Base.importHref()`. I keep getting second request with 404 with I use   `Polymer.Base.importHref()`.

**Comment by moderndeveloperllc** [comment]
@dman777 PSK 3 has redone all the code this issue was referring to and uses basePath amounts other things. Kinda had to know if this is still really an issue, or just needs to be closed out. @robdodson Is this just waiting to be cleaned up?

**Comment by dman777** [comment]
@moderndeveloperllc I think you are referring to a different issue with going pass one level in the url. This is a single level..... This is for the first level...one single level in the url `page('/user-account')` :

```javascript
page('/user-account', function() {
  var el = Polymer.dom(app.root).querySelector('user-account');
  if (Polymer.isInstance(el)) {
    app.route = 'user-account';
    return;
  }

  Polymer.Base.importHref(
    '/elements/account/user-account.html',
    () => {
      app.route = 'user-account';
      return;
    }
  )
});
```

It's not a issue if I do not use `Polymer.Base.importHref()`, history fall back works fine. Only when I use  `Polymer.Base.importHref()`. Then I am forced to use hash in the url. 

I think it's also important to mention that I am using browsersync. I know later on that was dropped in the PSK versions with no reload features(at least for awhile) but browsersync is still a popular tool.
