### ISSUE TITLE
Getting indentation warnings when doing 'gulp' in PSK w/ ES2015

### ISSUE THREAD

**Issue by JustinXinLiu** [PolymerElements/polymer-starter-kit#620]
Please see the screenshot below.

![gulp](https://cloud.githubusercontent.com/assets/1710184/11944070/0cab67be-a897-11e5-9462-a20ddfdda31b.PNG)

Looks like the **indentations** in the temporary files (i.e. *routing.html-script-1*, *my-greeting.html-script-0* & *my-list.html-script-0*) created by `$.htmlExtract()` are not right which makes *jscs* complain?

**Comment by robdodson** [comment]
Yeah I believe this is fixed on master. Can you try updating html extract to 0.1.0?

https://github.com/PolymerElements/polymer-starter-kit/blob/master/package.json#L13

Then delete node_modules and run `npm install` again. See if that fixes things?

**Comment by JustinXinLiu** [comment]
Thanks @robdodson but after deleting and re-installing all npm packages I am still getting the exact same error. :(

**Comment by samccone** [comment]
@JustinXinLiu to be clear even after you changed the version of gulp-html-extract?

**Comment by JustinXinLiu** [comment]
Yes @samccone , `npm list gulp-html-extract` returns
> gulp-html-extract@0.1.0

**Comment by robdodson** [comment]
oh! you also need to update your gulpfile to include this `strip` option.
https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L133

**Comment by JustinXinLiu** [comment]
That fixed it! Thanks @robdodson !
