### ISSUE TITLE
resolveUrl returns wrong path when serving with build/bundled

### ISSUE THREAD

**Issue by johnlim** [PolymerElements/polymer-starter-kit#913]
### Description

Calling resolveUrl in a nested element returns a different url when serving with `polymer serve` and `polymer serve build/bundled`
### Expected outcome

When calling `polymer serve build/bundled`, resolveUrl should return url with base url
### Actual outcome

When calling `polymer serve`, resolveUrl returns `http://localhost:8080/src/custom-element.html` but `polymer serve build/bundled` simply returns `custom-element.html`
### Live Demo

https://github.com/johnlim/polymer-starter-kit/tree/resolveUrl
### Steps to reproduce

1) clone the repo and switch to the branch resolveUrl
2) run bower install if necessary
3) run `polymer build` 
4) run `polyserve` and observe console output which prints out the resolved url as `http://localhost:8080/src/custom-element.html`
5) Clear application cache in browser
6) run `polyserve build/bundled` and observe console output which prints out the resolved url `custom-element.html`
### Browsers Affected

Only tried in Chrome

- [X ] Chrome

**Comment by doplumi** [comment]
This is also happening on my builds and it seems to be caused by vulcanize wrongly assigning `assetpath="/"` to the `dom-module` of the custom elements. Infact, going into the bundle and manually changing the assetpath to `src` (or whatever the element path is) removes the issue.

**Comment by johnlim** [comment]
@doplumi Thanks for confirming the issue. I've opened an issue with vulcanize which you can track [here](https://github.com/Polymer/vulcanize/issues/368)

**Comment by FredKSchott** [comment]
It looks like you guys are on the right track to figuring this out, everything in your psk branch looks correct right.

In the past its been more likely that this is a problem with build rather than bundling in vulcanize. Can you share the full output from running `polymer build --verbose`? That could help us expose the issue.

**Comment by johnlim** [comment]
@FredKSchott Thanks for looking into this. It's a pretty long output log though. Hope that helps.

[resolveUrl.txt](https://github.com/PolymerElements/polymer-starter-kit/files/460660/resolveUrl.txt)

**Comment by FredKSchott** [comment]
@johnlim thanks for sharing, everything looks fine in the build output. Can you try `polymer serve build/unbundled` and let us know what the results are for the unbundled build? That should tell us more definitively if this is an issue with building or bundling.

**Comment by johnlim** [comment]
@FredKSchott Thanks. Running `polymer serve build/unbundled` does not reproduce the issue. I should have added earlier that I tried `polymer serve`, `polymer serve build/unbundled` and `polymer serve build/bundled`. Only `polymer build/bundled` is having the said issue.

**Comment by doplumi** [comment]
I can confirm. Issue only happens while serving the build/bundled version of the project.

**Comment by FredKSchott** [comment]
Okay, thanks for the additional info. I'll take a deeper look into this as soon as I can

**Comment by robdodson** [comment]
looks like this is fixed upstream

**Comment by daniele-orlando** [comment]
I can still reproduce this bug on Polymer 1.9.3 and Polymer-Cli 1.5.2.
